language: python
sudo: false
cache: pip
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- which python; which pip
- pip list
- pip install -r tests/requirements.txt -r doc/requirements.txt
- pip list
- pip install -e .
- pip list
script:
- pytest --cov=calmap
- pushd doc && make html && popd
after_success:
- coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel --universal
  docs_dir: doc/.build/html
  user: marvint
  password: ${PYPI_PASSWORD}
  skip_cleanup: true
  on:
    tags: true
    python: '3.7'
